### ISSUE TITLE
Deploy changes to gh-page

### ISSUE THREAD

**Issue by operatino** [VinSpee/style-guide-guide#5]
Hi,

Could you please deploy changes from master repo to gh-pages? They are unsynced quite a while already.

**Comment by VinSpee** [comment]
done!

**Comment by operatino** [comment]
Actually no, site still is not synced with main README.md

**Comment by VinSpee** [comment]
if the changes in the PR were only made in in the readme, that's where they stay. The changes must also be made in the source.
